In [ ]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

In [ ]:
df1=pd.read_excel("/content/Finance_1.xlsx")

FileNotFoundError: [Errno 2] No such file or directory: '/content/Finance_1.xlsx'

In [ ]:
df2=pd.read_excel("/content/Finance_2.xlsx")

In [ ]:
df1.head(2)

In [ ]:
df2.head(2)

In [ ]:
df1.shape

In [ ]:
df1.size

In [ ]:
df1.isnull().sum()

In [ ]:
df1['emp_title']=df1['emp_title'].fillna("Not Provided")
df1['emp_length']=df1['emp_length'].fillna("unknown")
df1['desc']=df1['desc'].fillna("No description given")
mode_value = df1['title'].mode()[0]
df1['title'] = df1['title'].fillna(mode_value)

In [ ]:
df1.isnull().sum()

In [ ]:
from IPython.core import error
num_cols=df1.select_dtypes(include=["int64","float64"]).columns.tolist()
num_cols = [c for c in num_cols if c not in ['id', 'member_id']]
outliers_info={}
for col in num_cols:
    df1[col]=pd.to_numeric(df1[col],errors="coerce")
    Q1=df1[col].quantile(0.25)
    Q3=df1[col].quantile(0.75)
    IQR=Q3-Q1
    lower_bound=Q1-1*IQR
    upper_bound=Q3+1*IQR
    outliers=df1[(df1[col]<lower_bound)|(df1[col]>upper_bound)]
    outliers_info[col]={"count outliers":outliers.shape[0],"per outliers":(outliers.shape[0]/df1.shape[0])*100}
outliers_info

In [ ]:

num_cols=df1.select_dtypes(include=["int64","float64"]).columns.tolist()
num_cols = [c for c in num_cols if c not in ['id', 'member_id']]
for col in num_cols:
    df1[col]=pd.to_numeric(df1[col],errors="coerce")
    Q1=df1[col].quantile(0.25)
    Q3=df1[col].quantile(0.75)
    IQR=Q3-Q1
    lower_bound=Q1-1.5*IQR
    upper_bound=Q3+1.5*IQR
    df1[col]=df1[col].apply(lambda x:lower_bound if x < lower_bound else(upper_bound if x > upper_bound else x))

In [ ]:
import math
num_cols=df1.select_dtypes(include=["int64","float64"]).columns.tolist()
num_cols = [c for c in num_cols if c not in ['id', 'member_id']]
n_plots=len(num_cols)
n_cols=2
n_rows=math.ceil(n_plots/n_cols)
plt.figure(figsize=(8,n_rows*2))
for i,col in enumerate(num_cols,1):
   plt.subplot(n_rows,n_cols,i)
   sns.boxplot(y=df1[col])
   plt.title(f'boxplot of {col}')
plt.tight_layout()
plt.show()

In [ ]:
df1['emp_len_new'] = df1['emp_length'].fillna("Unknown")

In [ ]:
def emp_num(x):
    if  x == "Unknown":
        return 0
    x = x.strip()
    if x == "< 1 year":
        return 0.5
    x = x.replace("+", "")
    x = x.replace(" years", "")
    x = x.replace(" year", "")

    try:
        return int(x)  # integers for everything else
    except:
        return 0

df1['emp_len_new'] = df1['emp_length'].apply(emp_num)

df1['emp_length_display'] = df1['emp_len_new'].apply(lambda x: '0.5' if x == 0.5 else str(int(x)))

In [ ]:
df1.head(5)

In [ ]:
df1.drop(columns=['emp_len_new'], inplace=True)

In [ ]:
df1['term_num']=df1['term']
def num(x):
  if x == "36 months":
    return 36
  elif x == "60 months":
    return 60
  else:
    return 0
df1['term_num']=df1['term_num'].apply(num)

In [ ]:
df1.head(5)

In [ ]:
import re
for col in df1.select_dtypes(include=["object"]).columns:
    df1[col] = df1[col].str.replace(r"[^a-zA-Z0-9 .,'\-\/%]", "", regex=True)

In [ ]:
df1.duplicated()

In [ ]:
df1.head()

In [ ]:
df1.isna().sum()

In [ ]:
df1['emp_title']=df1['emp_title'].fillna("Not Provided")
df1['emp_length']=df1['emp_length'].fillna("unknown")
df1['desc']=df1['desc'].fillna("No description given")
mode_value = df1['title'].mode()[0]
df1['title'] = df1['title'].fillna(mode_value)

In [ ]:
df1.to_excel("cleaned_finance_1.xlsx")

In [ ]:
df1.isnull().sum()

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
df2=pd.read_excel("/content/Finance_2.xlsx")

In [ ]:
df2.head(3)

,id,delinq_2yrs,earliest_cr_line,inq_last_6mths,mths_since_last_delinq,mths_since_last_record,open_acc,pub_rec,revol_bal,revol_util,...,total_pymnt_inv,total_rec_prncp,total_rec_int,total_rec_late_fee,recoveries,collection_recovery_fee,last_pymnt_d,last_pymnt_amnt,next_pymnt_d,last_credit_pull_d
0,54734,0,1994-02-01,0,NaN,NaN,10,0,28854,0.521,...,21817.65,25000.0,4330.36,0.0,0.0,0.0,2011-10-01,7392.08,NaT,2012-08-01
1,55742,0,2000-10-01,0,NaN,NaN,7,0,33623,0.767,...,684.94,7000.0,1215.54,0.0,0.0,0.0,2011-06-01,228.48,NaT,2012-08-01
2,57245,0,1985-01-01,0,64.0,NaN,5,0,2584,0.404,...,1457.82,1200.0,257.82,0.0,0.0,0.0,2013-03-01,42.73,NaT,2016-05-01

In [ ]:
df2.shape

(39717, 25)

In [ ]:
df2.size

992925

In [ ]:
df2.isnull().sum()

id                             0
delinq_2yrs                    0
earliest_cr_line               0
inq_last_6mths                 0
mths_since_last_delinq     25682
mths_since_last_record     36931
open_acc                       0
pub_rec                        0
revol_bal                      0
revol_util                    50
total_acc                      0
initial_list_status            0
out_prncp                      0
out_prncp_inv                  0
total_pymnt                    0
total_pymnt_inv                0
total_rec_prncp                0
total_rec_int                  0
total_rec_late_fee             0
recoveries                     0
collection_recovery_fee        0
last_pymnt_d                  71
last_pymnt_amnt                0
next_pymnt_d               38577
last_credit_pull_d             2
dtype: int64

In [ ]:
df2['delinq_never'] = df2['mths_since_last_delinq'].isnull().astype(int)

In [ ]:
df2.head(5)

,id,delinq_2yrs,earliest_cr_line,inq_last_6mths,mths_since_last_delinq,mths_since_last_record,open_acc,pub_rec,revol_bal,revol_util,...,total_rec_prncp,total_rec_int,total_rec_late_fee,recoveries,collection_recovery_fee,last_pymnt_d,last_pymnt_amnt,next_pymnt_d,last_credit_pull_d,delinq_never
0,54734,0,1994-02-01,0,NaN,NaN,10,0,28854,0.521,...,25000.00,4330.36,0.0,0.0,0.0,2011-10-01,7392.08,NaT,2012-08-01,1
1,55742,0,2000-10-01,0,NaN,NaN,7,0,33623,0.767,...,7000.00,1215.54,0.0,0.0,0.0,2011-06-01,228.48,NaT,2012-08-01,1
2,57245,0,1985-01-01,0,64.0,NaN,5,0,2584,0.404,...,1200.00,257.82,0.0,0.0,0.0,2013-03-01,42.73,NaT,2016-05-01,0
3,57416,0,1996-12-01,1,58.0,NaN,14,0,3511,0.256,...,10800.00,2407.76,0.0,0.0,0.0,2012-11-01,398.00,NaT,2016-05-01,0
4,58915,0,2000-11-01,1,NaN,NaN,3,0,33667,0.732,...,5024.99,818.88,0.0,0.0,0.0,2011-04-01,162.63,NaT,2014-03-01,1

In [ ]:
df2['record_never'] = df2['mths_since_last_record'].isnull().astype(int)

In [ ]:
df2['revol_util']=df2['revol_util'].fillna(df2['revol_util'].median())

In [ ]:
bins = [0, 0.25, 0.5, 0.75, 1]
labels = ['Low', 'Medium', 'High', 'Very High']
df2['revol_util_category'] = pd.cut(df2['revol_util'], bins=bins, labels=labels, include_lowest=True)

In [ ]:
df2.head(10)

,id,delinq_2yrs,earliest_cr_line,inq_last_6mths,mths_since_last_delinq,mths_since_last_record,open_acc,pub_rec,revol_bal,revol_util,...,total_rec_late_fee,recoveries,collection_recovery_fee,last_pymnt_d,last_pymnt_amnt,next_pymnt_d,last_credit_pull_d,delinq_never,record_never,revol_util_category
0,54734,0,1994-02-01,0,NaN,NaN,10,0,28854,0.521,...,0.0,0.00,0.00,2011-10-01,7392.08,NaT,2012-08-01,1,1,High
1,55742,0,2000-10-01,0,NaN,NaN,7,0,33623,0.767,...,0.0,0.00,0.00,2011-06-01,228.48,NaT,2012-08-01,1,1,Very High
2,57245,0,1985-01-01,0,64.0,NaN,5,0,2584,0.404,...,0.0,0.00,0.00,2013-03-01,42.73,NaT,2016-05-01,0,1,Medium
3,57416,0,1996-12-01,1,58.0,NaN,14,0,3511,0.256,...,0.0,0.00,0.00,2012-11-01,398.00,NaT,2016-05-01,0,1,Medium
4,58915,0,2000-11-01,1,NaN,NaN,3,0,33667,0.732,...,0.0,0.00,0.00,2011-04-01,162.63,NaT,2014-03-01,1,1,High
5,59006,1,1998-07-01,0,13.0,0.0,13,0,4740,0.395,...,0.0,0.00,0.00,2012-10-01,111.23,NaT,2012-09-01,0,0,Medium
6,61390,0,1993-05-01,0,NaN,NaN,11,0,50807,0.510,...,0.0,0.00,0.00,2012-03-01,1454.31,NaT,2012-03-01,1,1,High
7,61419,0,2001-06-01,0,38.0,63.0,5,1,3839,0.768,...,0.0,42.84,1.06,2012-10-01,194.02,NaT,2013-03-01,0,0,Very High
8,62102,0,2006-06-01,0,NaN,NaN,7,0,3198,0.511,...,0.0,0.00,0.00,2011-02-01,2592.23,NaT,2013-03-01,1,1,High
9,65426,0,1995-08-01,0,0.0,0.0,14,0,24220,0.686,...,0.0,0.00,0.00,2011-06-01,131.22,NaT,2016-05-01,0,0,High

In [ ]:
df2['total_pymnt_inv']=df2['total_pymnt_inv'].fillna(df2['total_pymnt_inv'].median())

In [ ]:
df2['last_pymnt_d'] = pd.to_datetime(df2['last_pymnt_d'], errors='coerce')
df2['has_last_payment'] = df2['last_pymnt_d'].notna()

In [ ]:
df2['next_pymnt_d'] = pd.to_datetime(df2['next_pymnt_d'], errors='coerce')
df2['has_next_payment'] = df2['next_pymnt_d'].notna()

In [ ]:
df2.head(10)

,id,delinq_2yrs,earliest_cr_line,inq_last_6mths,mths_since_last_delinq,mths_since_last_record,open_acc,pub_rec,revol_bal,revol_util,...,collection_recovery_fee,last_pymnt_d,last_pymnt_amnt,next_pymnt_d,last_credit_pull_d,delinq_never,record_never,revol_util_category,has_last_payment,has_next_payment
0,54734,0,1994-02-01,0,NaN,NaN,10,0,28854,0.521,...,0.00,2011-10-01,7392.08,NaT,2012-08-01,1,1,High,True,False
1,55742,0,2000-10-01,0,NaN,NaN,7,0,33623,0.767,...,0.00,2011-06-01,228.48,NaT,2012-08-01,1,1,Very High,True,False
2,57245,0,1985-01-01,0,64.0,NaN,5,0,2584,0.404,...,0.00,2013-03-01,42.73,NaT,2016-05-01,0,1,Medium,True,False
3,57416,0,1996-12-01,1,58.0,NaN,14,0,3511,0.256,...,0.00,2012-11-01,398.00,NaT,2016-05-01,0,1,Medium,True,False
4,58915,0,2000-11-01,1,NaN,NaN,3,0,33667,0.732,...,0.00,2011-04-01,162.63,NaT,2014-03-01,1,1,High,True,False
5,59006,1,1998-07-01,0,13.0,0.0,13,0,4740,0.395,...,0.00,2012-10-01,111.23,NaT,2012-09-01,0,0,Medium,True,False
6,61390,0,1993-05-01,0,NaN,NaN,11,0,50807,0.510,...,0.00,2012-03-01,1454.31,NaT,2012-03-01,1,1,High,True,False
7,61419,0,2001-06-01,0,38.0,63.0,5,1,3839,0.768,...,1.06,2012-10-01,194.02,NaT,2013-03-01,0,0,Very High,True,False
8,62102,0,2006-06-01,0,NaN,NaN,7,0,3198,0.511,...,0.00,2011-02-01,2592.23,NaT,2013-03-01,1,1,High,True,False
9,65426,0,1995-08-01,0,0.0,0.0,14,0,24220,0.686,...,0.00,2011-06-01,131.22,NaT,2016-05-01,0,0,High,True,False

In [ ]:
import pandas as pd

In [ ]:
df2.head(10)

,id,delinq_2yrs,earliest_cr_line,inq_last_6mths,mths_since_last_delinq,mths_since_last_record,open_acc,pub_rec,revol_bal,revol_util,...,collection_recovery_fee,last_pymnt_d,last_pymnt_amnt,next_pymnt_d,last_credit_pull_d,delinq_never,record_never,revol_util_category,has_last_payment,has_next_payment
0,54734,0,1994-02-01,0,NaN,NaN,10,0,28854,0.521,...,0.00,2011-10-01,7392.08,NaT,2012-08-01,1,1,High,True,False
1,55742,0,2000-10-01,0,NaN,NaN,7,0,33623,0.767,...,0.00,2011-06-01,228.48,NaT,2012-08-01,1,1,Very High,True,False
2,57245,0,1985-01-01,0,64.0,NaN,5,0,2584,0.404,...,0.00,2013-03-01,42.73,NaT,2016-05-01,0,1,Medium,True,False
3,57416,0,1996-12-01,1,58.0,NaN,14,0,3511,0.256,...,0.00,2012-11-01,398.00,NaT,2016-05-01,0,1,Medium,True,False
4,58915,0,2000-11-01,1,NaN,NaN,3,0,33667,0.732,...,0.00,2011-04-01,162.63,NaT,2014-03-01,1,1,High,True,False
5,59006,1,1998-07-01,0,13.0,0.0,13,0,4740,0.395,...,0.00,2012-10-01,111.23,NaT,2012-09-01,0,0,Medium,True,False
6,61390,0,1993-05-01,0,NaN,NaN,11,0,50807,0.510,...,0.00,2012-03-01,1454.31,NaT,2012-03-01,1,1,High,True,False
7,61419,0,2001-06-01,0,38.0,63.0,5,1,3839,0.768,...,1.06,2012-10-01,194.02,NaT,2013-03-01,0,0,Very High,True,False
8,62102,0,2006-06-01,0,NaN,NaN,7,0,3198,0.511,...,0.00,2011-02-01,2592.23,NaT,2013-03-01,1,1,High,True,False
9,65426,0,1995-08-01,0,0.0,0.0,14,0,24220,0.686,...,0.00,2011-06-01,131.22,NaT,2016-05-01,0,0,High,True,False

In [ ]:
df2.isnull().sum()

id                             0
delinq_2yrs                    0
earliest_cr_line               0
inq_last_6mths                 0
mths_since_last_delinq     25682
mths_since_last_record     36931
open_acc                       0
pub_rec                        0
revol_bal                      0
revol_util                     0
total_acc                      0
initial_list_status            0
out_prncp                      0
out_prncp_inv                  0
total_pymnt                    0
total_pymnt_inv                0
total_rec_prncp                0
total_rec_int                  0
total_rec_late_fee             0
recoveries                     0
collection_recovery_fee        0
last_pymnt_d                  71
last_pymnt_amnt                0
next_pymnt_d               38577
last_credit_pull_d             2
delinq_never                   0
record_never                   0
revol_util_category            0
has_last_payment               0
has_next_payment               0
dtype: int64

In [ ]:
df2['total_rec_late_fee'] = df2['total_rec_late_fee'].round(2)
df2['recoveries'] = df2['recoveries'].round(2)
df2['last_pymnt_amnt'] = df2['last_pymnt_amnt'].round(2)
df2['collection_recovery_fee']=df2['collection_recovery_fee'].round(2)

In [ ]:
df2.head(5)

,id,delinq_2yrs,earliest_cr_line,inq_last_6mths,mths_since_last_delinq,mths_since_last_record,open_acc,pub_rec,revol_bal,revol_util,...,collection_recovery_fee,last_pymnt_d,last_pymnt_amnt,next_pymnt_d,last_credit_pull_d,delinq_never,record_never,revol_util_category,has_last_payment,has_next_payment
0,54734,0,1994-02-01,0,NaN,NaN,10,0,28854,0.521,...,0.0,2011-10-01,7392.08,NaT,2012-08-01,1,1,High,True,False
1,55742,0,2000-10-01,0,NaN,NaN,7,0,33623,0.767,...,0.0,2011-06-01,228.48,NaT,2012-08-01,1,1,Very High,True,False
2,57245,0,1985-01-01,0,64.0,NaN,5,0,2584,0.404,...,0.0,2013-03-01,42.73,NaT,2016-05-01,0,1,Medium,True,False
3,57416,0,1996-12-01,1,58.0,NaN,14,0,3511,0.256,...,0.0,2012-11-01,398.00,NaT,2016-05-01,0,1,Medium,True,False
4,58915,0,2000-11-01,1,NaN,NaN,3,0,33667,0.732,...,0.0,2011-04-01,162.63,NaT,2014-03-01,1,1,High,True,False

In [ ]:
df2['total_pymnt'] = df2['total_pymnt'].round(2)
df2['total_pymnt_inv'] = df2['total_pymnt_inv'].round(2)
df2['total_rec_prncp']=df2['total_rec_prncp'].round(2)

In [ ]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 39717 entries, 0 to 39716
Data columns (total 30 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   id                       39717 non-null  int64
 1   delinq_2yrs              39717 non-null  int64
 2   earliest_cr_line         39717 non-null  datetime64[ns]
 3   inq_last_6mths           39717 non-null  int64
 4   mths_since_last_delinq   14035 non-null  float64
 5   mths_since_last_record   2786 non-null   float64
 6   open_acc                 39717 non-null  int64
 7   pub_rec                  39717 non-null  int64
 8   revol_bal                39717 non-null  int64
 9   revol_util               39717 non-null  float64
 10  total_acc                39717 non-null  int64
 11  initial_list_status      39717 non-null  object
 12  out_prncp                39717 non-null  float64
 13  out_prncp_inv            39717 non-null  float64
 14  total_pymnt              39717 non-null  float64
 15  total_pymnt_inv          39717 non-null  float64
 16  total_rec_prncp          39717 non-null  float64
 17  total_rec_int            39717 non-null  float64
 18  total_rec_late_fee       39717 non-null  float64
 19  recoveries               39717 non-null  float64
 20  collection_recovery_fee  39717 non-null  float64
 21  last_pymnt_d             39646 non-null  datetime64[ns]
 22  last_pymnt_amnt          39717 non-null  float64
 23  next_pymnt_d             1140 non-null   datetime64[ns]
 24  last_credit_pull_d       39715 non-null  datetime64[ns]
 25  delinq_never             39717 non-null  int64
 26  record_never             39717 non-null  int64
 27  revol_util_category      39717 non-null  category
 28  has_last_payment         39717 non-null  bool
 29  has_next_payment         39717 non-null  bool
dtypes: bool(2), category(1), datetime64[ns](4), float64(13), int64(9), object(1)
memory usage: 8.3+ MB

In [ ]:
df2.to_excel("cleaned_finance_2.xlsx")

In [ ]:
import pandas as pd

In [ ]:
df2=pd.read_excel("/content/cleaned_finance_2 (2).xlsx")

BadZipFile: File is not a zip file

In [ ]:
import pandas as pd
import matplotlib. pyplot as plt
import numpy as np
import seaborn as sns

In [ ]:
df1=pd.read_excel("/content/cleaned_finance_1.xlsx")

In [ ]:
df1.head(5)

,Unnamed: 0,id,member_id,loan_amnt,funded_amnt,funded_amnt_inv,term,int_rate,installment,grade,...,loan_status,pymnt_plan,desc,purpose,title,zip_code,addr_state,dti,emp_length_display,term_num
0,0,54734,80364,25000,25000,19080.057200,36 months,0.1189,826.42,B,...,Fully Paid,n,Due to a lack of personal finance education an...,debtconsolidation,Debt consolidation for on-time payer,941xx,CA,19.48,0.5,36
1,1,55742,114426,7000,7000,672.803839,36 months,0.1071,228.22,B,...,Fully Paid,n,Just want to pay off the last bit of credit ca...,creditcard,Credit Card payoff,112xx,NY,14.29,0.5,36
2,2,57245,138150,1200,1200,1200.000000,36 months,0.1311,40.50,C,...,Fully Paid,n,"If funded, I would use this loan consolidate t...",debtconsolidation,zxcvb,777xx,TX,5.47,10.0,36
3,3,57416,139635,10800,10800,10691.551050,36 months,0.1357,366.86,C,...,Fully Paid,n,I currently have a personal loan with Citifina...,debtconsolidation,Nicolechr1978,067xx,CT,11.63,6.0,36
4,4,58915,153417,7500,5025,557.087228,36 months,0.1008,162.34,B,...,Fully Paid,n,Hi Thanks for stopping by. I've accru...,debtconsolidation,sdguy,921xx,CA,8.10,3.0,36

In [ ]:
df2 = pd.read_csv("/content/finance_dataset_2.csv", low_memory=False)

In [ ]:
df2.head(5)

,id,delinq_2yrs,earliest_cr_line,inq_last_6mths,mths_since_last_delinq,mths_since_last_record,open_acc,pub_rec,revol_bal,revol_util,...,total_rec_prncp,total_rec_int,total_rec_late_fee,recoveries,collection_recovery_fee,last_pymnt_d,last_pymnt_amnt,last_credit_pull_d,revol_util_range,next_pymnt_d
0,296737,0,01-Oct-91,0,NaN,NaN,4,0,84,0.01,...,10000.0,1185.04,0.0,0.0,0.0,01-Mar-14,1279.88,01-May-16,very low,NaN
1,362148,0,01-Jan-92,0,NaN,NaN,7,0,18917,0.33,...,10000.0,1424.15,0.0,0.0,0.0,01-Jun-11,1891.69,01-May-16,medium,NaN
2,364755,0,01-Feb-04,0,NaN,NaN,8,0,14411,0.21,...,10000.0,1649.98,0.0,0.0,0.0,01-Dec-11,348.39,01-May-16,low,NaN
3,371779,0,01-Jul-84,0,NaN,NaN,16,0,10942,0.57,...,10000.0,2322.38,0.0,0.0,0.0,01-Jan-12,354.86,01-May-16,high,NaN
4,396913,0,01-Dec-99,0,NaN,NaN,9,0,20344,0.86,...,10000.0,2377.68,0.0,0.0,0.0,01-May-12,364.77,01-May-16,very high,NaN

In [ ]:
data=pd.merge(df1,df2,how="left",on="id")

In [ ]:
 data['issue_d'] = pd.to_datetime(data['issue_d'])
data.groupby(data['issue_d'].dt.year)['loan_amnt'].sum()

issue_d
2026    440928100
Name: loan_amnt, dtype: int64

In [ ]:
data.groupby(['grade','sub_grade'])['revol_bal'].sum().reset_index()

   grade sub_grade  revol_bal
0      A        A1   11365196
1      A        A2   14004780
2      A        A3   19543922
3      A        A4   34557156
4      A        A5   35303045
5      B        B1   21842079
6      B        B2   26478439
7      B        B3   39723554
8      B        B4   35405811
9      B        B5   37858666
10     C        C1   29384926
11     C        C2   27321114
12     C        C3   20531370
13     C        C4   16867691
14     C        C5   16015609
15     D        D1   12130255
16     D        D2   18570972
17     D        D3   16793781
18     D        D4   13742947
19     D        D5   13252474
20     E        E1   11132588
21     E        E2   10242033
22     E        E3    9039059
23     E        E4    7990991
24     E        E5    7669868
25     F        F1    5840746
26     F        F2    4528248
27     F        F3    3175435
28     F        F4    2551064
29     F        F5    2187323
30     G        G1    1808763
31     G        G2    1729627
32     G        G3     832193
33     G        G4    1390628
34     G        G5     701515

In [ ]:
data.groupby('verification_status')['total_pymnt'].sum().reset_index()

  verification_status   total_pymnt
0        Not Verified  1.535414e+08
1     Source Verified  1.092707e+08
2            Verified  2.198923e+08

In [ ]:
data['issue_d'] = pd.to_datetime(data['issue_d'], errors='coerce')
data['Month'] = data['issue_d'].dt.month
data.groupby(['addr_state','Month'])['loan_status'].count().reset_index()

    addr_state  Month  loan_status
0           AK      1            6
1           AK      2            2
2           AK      3            8
3           AK      4            4
4           AK      5            9
..         ...    ...          ...
546         WY      8            2
547         WY      9            7
548         WY     10           12
549         WY     11            4
550         WY     12            6

[551 rows x 3 columns]

In [ ]:
data['last_pymnt_d'] = pd.to_datetime(data['last_pymnt_d'], errors='coerce')

/tmp/ipython-input-3732276047.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  data['last_pymnt_d'] = pd.to_datetime(data['last_pymnt_d'], errors='coerce')

In [ ]:
data.groupby('home_ownership')['last_pymnt_d'].agg(['count','max']).reset_index()

  home_ownership  count        max
0       MORTGAGE  17645 2016-05-01
1           NONE      3 2011-02-01
2          OTHER     98 2015-07-01
3            OWN   3053 2016-05-01
4           RENT  18847 2016-05-01

In [ ]:
data.columns

Index(['Unnamed: 0', 'id', 'member_id', 'loan_amnt', 'funded_amnt',
       'funded_amnt_inv', 'term', 'int_rate', 'installment', 'grade',
       'sub_grade', 'emp_title', 'emp_length', 'home_ownership', 'annual_inc',
       'verification_status', 'issue_d', 'loan_status', 'pymnt_plan', 'desc',
       'purpose', 'title', 'zip_code', 'addr_state', 'dti',
       'emp_length_display', 'term_num', 'delinq_2yrs', 'earliest_cr_line',
       'inq_last_6mths', 'mths_since_last_delinq', 'mths_since_last_record',
       'open_acc', 'pub_rec', 'revol_bal', 'revol_util', 'total_acc',
       'initial_list_status', 'out_prncp', 'out_prncp_inv', 'total_pymnt',
       'total_pymnt_inv', 'total_rec_prncp', 'total_rec_int',
       'total_rec_late_fee', 'recoveries', 'collection_recovery_fee',
       'last_pymnt_d', 'last_pymnt_amnt', 'last_credit_pull_d',
       'revol_util_range', 'next_pymnt_d'],
      dtype='object')